kerchunk_pipeline:
  s3:
    endpoint_url: "https://projects.pawsey.org.au"
    bucket: "webviz"
    region_name: "us-east-1"
    project_scope: "jchew"
    
  source_flows:
    - id: "ecmwf_weekly_nc"
      enabled: true
      mode: "prefix_glob"
      prefix: "ECMWF/"
      key_glob: "ECMWF/????/??/??.nc"

    - id: "dpird_final_singleton"
      enabled: true
      mode: "exact_key"
      exact_key: "DPIRD/dpird_wa_stations.nc"

  output:
    staging_volume_path: "acacia_refs_staging"
    ledger_path: "acacia_refs_staging/_state/inventory_ledger.json"
    temp_path: "acacia_refs_temp"

  execution:
    max_workers: 5
    memory_limit_gb: "1GB" # 1GB per worker
    list_page_size: 1000
    parquet_record_size: 100000 # Will generate refs.0.parq, refs.1.parq, etc. if total refs > parquet_record_size.
    categorical_threshold: 10 # Only applicable for vz.open_mfadataset(). If vds has <10 unique S3 URLs, it will store the S3 URLs in a lookup table for quick access. Otherwise, it will store the S3 URLs in the parquet file and read them on demand.
