name: pipeline-ci
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v6
      
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install pytest and coverage
        run: |
          python -m pip install --upgrade pip
          # Not installing full dependencies to speed up the CI, only pytest and coverage are needed for testing
          pip install pytest pytest-cov
      
      - name: Run tests with coverage
        run: |
          pytest --cov-report=xml
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true
